In [40]:
!git clone https://github.com/miguelperezenciso/DLpipeline.git/

Cloning into 'DLpipeline'...
remote: Enumerating objects: 279, done.
remote: Total 279 (delta 0), reused 0 (delta 0), pack-reused 279
Receiving objects: 100% (279/279), 1.31 MiB | 8.70 MiB/s, done.
Resolving deltas: 100% (161/161), done.


In [0]:
!mv DLpipeline/DATA ./

In [0]:
# Load modules needed
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

# keras items 
from keras.models import Sequential
from keras.layers import Dense, Activation

# Load the dataset as a pandas data frame
# X is a N by nSNP array with SNP genotypes
X = pd.read_csv('DATA/wheat.X', header=None, sep='\s+')
# Y is a N b nTRAIT array with phenotypes
Y = pd.read_csv('DATA/wheat.Y', header=None, sep='\s+')
# The first trait is analyzed
y = Y[0] 

# Data partitioning into train and test (20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# no. of SNPs in data
nSNP = X_train.shape[1] 

In [43]:
# Instantiate model
model = Sequential()

# (We assume optimum DL configuration has been determined)
# Add first layer containing 64 neurons
model.add(Dense(64, input_dim=nSNP))
model.add(Activation('relu'))
# Add second layer, with 32 neurons
model.add(Dense(32))
model.add(Activation('relu'))
# Last, output layer contains one neuron (ie, target is a real numeric value)
model.add(Dense(1))

# Model Compiling 
model.compile(loss='mean_squared_error', optimizer='sgd')

# list some properties of the network
model.summary()

Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_32 (Dense)             (None, 64)                81920     
_________________________________________________________________
activation_23 (Activation)   (None, 64)                0         
_________________________________________________________________
dense_33 (Dense)             (None, 32)                2080      
_________________________________________________________________
activation_24 (Activation)   (None, 32)                0         
_________________________________________________________________
dense_34 (Dense)             (None, 1)                 33        
Total params: 84,033
Trainable params: 84,033
Non-trainable params: 0
_________________________________________________________________


In [44]:
# Training
model.fit(X_train, y_train, epochs=60)

Epoch 1/60
479/479 [==============================] - 0s 234us/step - loss: 2.5541
Epoch 2/60
479/479 [==============================] - 0s 108us/step - loss: 0.9776
Epoch 3/60
479/479 [==============================] - 0s 111us/step - loss: 0.9442
Epoch 4/60
479/479 [==============================] - 0s 115us/step - loss: 0.9270
Epoch 5/60
479/479 [==============================] - 0s 113us/step - loss: 0.9012
Epoch 6/60
479/479 [==============================] - 0s 142us/step - loss: 0.9364
Epoch 7/60
479/479 [==============================] - 0s 147us/step - loss: 0.8865
Epoch 8/60
479/479 [==============================] - 0s 121us/step - loss: 0.8530
Epoch 9/60
479/479 [==============================] - 0s 138us/step - loss: 0.8113
Epoch 10/60
479/479 [==============================] - 0s 129us/step - loss: 0.8369
Epoch 11/60
479/479 [==============================] - 0s 118us/step - loss: 0.8435
Epoch 12/60
479/479 [==============================] - 0s 141us/step - loss: 0.8413
E

In [45]:
# Computes squared error in prediction
mse_prediction = model.evaluate(X_test, y_test)
mse_prediction

120/120 [==============================] - 0s 223us/step


0.7836752891540527

In [0]:
# Load modules needed
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

# keras items 
from keras.models import Sequential
from keras.layers import Dense, Activation

# Load the dataset as a pandas data frame
# X is a N by nSNP array with SNP genotypes
X = pd.read_csv('DATA/wheat.X', header=None, sep='\s+')
# Y is a N b nTRAIT array with phenotypes
Y = pd.read_csv('DATA/wheat.Y', header=None, sep='\s+')
# The first trait is analyzed
y = Y[0] 

# Data partitioning into train and test (20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# no. of SNPs in data
nSNP = X_train.shape[1] 

In [0]:
from keras.models import Sequential
from keras.layers import Dense, Activation 
from keras.layers import Flatten, Conv1D, MaxPooling1D

nStride=3 # stride between convolutions
nFilter=32 # no. of convolutions

model = Sequential()
# add convolutional layer
model.add(Conv1D(nFilter, 
kernel_size=3, 
strides=nStride, 		
input_shape=(nSNP,1)))
# add pooling layer: here takes maximum of two consecutive values
model.add(MaxPooling1D(pool_size=2))
# Solutions above are linearized to accommodate a standard layer
model.add(Flatten())
model.add(Dense(64))
model.add(Activation('relu'))
model.add(Dense(32))
model.add(Activation('softplus'))
model.add(Dense(1))

In [48]:
# Model Compiling 
model.compile(loss='mean_squared_error', optimizer='sgd')

# list some properties of the network
model.summary()

Model: "sequential_11"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_1 (Conv1D)            (None, 426, 32)           128       
_________________________________________________________________
max_pooling1d_1 (MaxPooling1 (None, 213, 32)           0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 6816)              0         
_________________________________________________________________
dense_35 (Dense)             (None, 64)                436288    
_________________________________________________________________
activation_25 (Activation)   (None, 64)                0         
_________________________________________________________________
dense_36 (Dense)             (None, 32)                2080      
_________________________________________________________________
activation_26 (Activation)   (None, 32)              

In [49]:
# Training
model.fit(np.expand_dims(X_train, axis=-1), y_train, epochs=60)

Epoch 1/60
479/479 [==============================] - 4s 9ms/step - loss: 0.9948
Epoch 2/60
479/479 [==============================] - 0s 171us/step - loss: 1.0062
Epoch 3/60
479/479 [==============================] - 0s 180us/step - loss: 0.9145
Epoch 4/60
479/479 [==============================] - 0s 165us/step - loss: 0.9232
Epoch 5/60
479/479 [==============================] - 0s 170us/step - loss: 0.8233
Epoch 6/60
479/479 [==============================] - 0s 187us/step - loss: 0.7434
Epoch 7/60
479/479 [==============================] - 0s 174us/step - loss: 0.7433
Epoch 8/60
479/479 [==============================] - 0s 179us/step - loss: 0.6402
Epoch 9/60
479/479 [==============================] - 0s 172us/step - loss: 0.6374
Epoch 10/60
479/479 [==============================] - 0s 176us/step - loss: 0.5802
Epoch 11/60
479/479 [==============================] - 0s 187us/step - loss: 0.6657
Epoch 12/60
479/479 [==============================] - 0s 166us/step - loss: 0.5622
Epo

In [50]:
# Computes squared error in prediction
mse_prediction = model.evaluate(np.expand_dims(X_test, axis=-1), y_test)
mse_prediction

120/120 [==============================] - 0s 377us/step


0.6985671639442443

In [0]:
# Diabetes Classification

In [0]:
# Load modules needed
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

# keras items 
from keras.models import Sequential
from keras.layers import Dense, Activation, Dropout

In [0]:
filename = 'diabetes.csv'
dataframe = pd.read_csv(filename)

array = dataframe.values
X = array[:, 0:8]
y = array[:, 8]

In [54]:
array

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [0]:
from sklearn.model_selection import train_test_split

# Data partitioning into train and test (20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [56]:
X_train.shape

(614, 8)

In [57]:
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [58]:
y

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 0., 0., 0.

In [59]:
# Instantiate model
model = Sequential()


model.add(Dense(512, input_dim=(8)))
model.add(Activation('relu'))
model.add(Dense(256))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(256))
model.add(Activation('relu'))
model.add(Dense(256))
model.add(Activation('relu'))
model.add(Dense(1, activation="sigmoid"))

# Model Compiling 
model.compile(loss='binary_crossentropy', optimizer='rmsprop', metrics=['accuracy'])

# list some properties of the network
model.summary()

Model: "sequential_12"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_38 (Dense)             (None, 512)               4608      
_________________________________________________________________
activation_27 (Activation)   (None, 512)               0         
_________________________________________________________________
dense_39 (Dense)             (None, 256)               131328    
_________________________________________________________________
activation_28 (Activation)   (None, 256)               0         
_________________________________________________________________
dropout_4 (Dropout)          (None, 256)               0         
_________________________________________________________________
dense_40 (Dense)             (None, 256)               65792     
_________________________________________________________________
activation_29 (Activation)   (None, 256)             

In [60]:
# Training
model.fit(X_train, y_train, epochs=100)

Epoch 1/100
614/614 [==============================] - 0s 408us/step - loss: 2.2813 - accuracy: 0.5733
Epoch 2/100
614/614 [==============================] - 0s 176us/step - loss: 0.9915 - accuracy: 0.5798
Epoch 3/100
614/614 [==============================] - 0s 177us/step - loss: 0.8421 - accuracy: 0.5717
Epoch 4/100
614/614 [==============================] - 0s 168us/step - loss: 0.8845 - accuracy: 0.6107
Epoch 5/100
614/614 [==============================] - 0s 217us/step - loss: 0.7505 - accuracy: 0.5993
Epoch 6/100
614/614 [==============================] - 0s 162us/step - loss: 0.7433 - accuracy: 0.5993
Epoch 7/100
614/614 [==============================] - 0s 182us/step - loss: 0.7181 - accuracy: 0.6352
Epoch 8/100
614/614 [==============================] - 0s 167us/step - loss: 0.6782 - accuracy: 0.6124
Epoch 9/100
614/614 [==============================] - 0s 190us/step - loss: 0.6948 - accuracy: 0.6270
Epoch 10/100
614/614 [==============================] - 0s 170us/step - l

In [61]:
model.evaluate(X_train, y_train)

614/614 [==============================] - 0s 160us/step


[0.4698728003602851, 0.7817589640617371]

In [62]:
model.evaluate(X_test, y_test)

154/154 [==============================] - 0s 107us/step


[0.7353000315752897, 0.701298713684082]